// article
export const REQ_ARTICLEINFOS = 'REQ_ARTICLEINFOS'
export const RECIVE_ARTICLEINFOS = 'RECIVE_ARTICLEINFOS'

export const REQ_ADD_ARTICLE = 'REQ_ADD_ARTICLE'
export const DONE_ADD_ARTICLE = 'DONE_ADD_ARTICLE'
export const FAILED_ADD_ARTICLE = 'FAILED_ADD_ARTICLE'

export const REQ_DEL_ARTICLE = 'REQ_DEL_ARTICLE'
export const DONE_DEL_ARTICLE = 'DONE_DEL_ARTICLE'
export const FAILED_DEL_ARTICLE = 'FAILED_DEL_ARTICLE'

export const REQ_FIND_ARTICLE = 'REQ_FIND_ARTICLE'
export const DONE_FIND_ARTICLE = 'DONE_FIND_ARTICLE'
export const FAILED_FIND_ARTICLE = 'FAILED_FIND_ARTICLE'

export const REQ_EDIT_ARTICLE = 'REQ_EDIT_ARTICLE'
export const DONE_EDIT_ARTICLE = 'DONE_EDIT_ARTICLE'
export const FAILED_EDIT_ARTICLE = 'FAILED_EDIT_ARTICLE'

export default {

    // category
    REQUEST_CATEGORY_LIST: 'REQUEST_CATEGORY_LIST',
    RECIVE_CATEGORY_LIST: 'RECIVE_CATEGORY_LIST',
    SHOW_CATEGORY: 'SHOW_CATEGORY',
    REQUEST_ADD_CATEGORY: 'REQUEST_ADD_CATEGORY',
    DONE_ADD_CATEGORY: 'DONE_ADD_CATEGORY',
    FAILED_ADD_CATEGORY: 'FAILED_ADD_CATEGORY',
    REQUEST_DELETE_CATEGORY: 'REQUEST_DELETE_CATEGORY',
    DONE_DELETE_CATEGORY: 'DONE_DELETE_CATEGORY',
    FAILED_DELETE_CATEGORY: 'FAILED_DELETE_CATEGORY',
    REQUEST_UPDATE_CATEGORY: 'REQUEST_UPDATE_CATEGORY',
    DONE_UPDATE_CATEGORY: 'DONE_UPDATE_CATEGORY',
    FAILED_UPDATE_CATEGORY: 'FAILED_UPDATE_CATEGORY',
    REQUEST_RECOMMEND_CATEGORY: 'RREQUEST_RECOMMEND_CATEGORY',
    DONE_RECOMMEND_CATEGORY: 'DONE_RECOMMEND_CATEGORY',
    FAILED_RECOMMEND_CATEGORY: 'FAILED_RECOMMEND_CATEGORY',

    // tag
    REQUEST_TAG_LIST: 'REQUEST_TAG_LIST',
    RECIVE_TAG_LIST: 'RECIVE_TAG_LIST',
    REQUEST_ADD_TAG: 'REQUEST_ADD_TAG',
    DONE_ADD_TAG: 'DONE_ADD_TAG',
    FAILED_ADD_TAG: 'FAILED_ADD_TAG',
    REQUEST_UPDATE_TAG: 'REQUEST_UPDATE_TAG',
    DONE_UPDATE_TAG: 'DONE_UPDATE_TAG',
    FAILED_UPDATE_TAG: 'FAILED_UPDATE_TAG',
    REQUEST_DELETE_TAG: 'REQUEST_DELETE_TAG',
    DONE_DELETE_TAG: 'DONE_DELETE_TAG',
    FAILED_DELETE_TAG: 'FAILED_DELETE_TAG'
}